version: '2'

services:
  microservice1:
    image: microservice1
    build:
      context: ./MicroService1
      dockerfile: Dockerfile

  microservice2:
    image: microservice2
    build:
      context: ./MicroService2
      dockerfile: Dockerfile

  webappmicroservice:
    image: webappmicroservice
    build:
      context: ./WebAppMicroService
      dockerfile: Dockerfile
