version: '2'

services:
  microservice1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  microservice2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
